### ISSUE TITLE
Updation of url : https://www.dropbox.com/s/a84otqrg6u1c5je/stats.zip?dl=1 required

### ISSUE THREAD

**Issue by devamanyu** [cbaziotis/ekphrasis#11]
Unable to download word statistics file due to a broken [link](https://www.dropbox.com/s/a84otqrg6u1c5je/stats.zip?dl=1). Please update.

**Comment by bhuthesh** [comment]
Had a service deployed in production broken due to dropbox blocking access to this file. Fortunately had a a cached version of the statistics file. Is there a way to host them somewhere and update the URL?

**Comment by memat100** [comment]
I have the same issue. Can you please update the link.

**Comment by bhuthesh** [comment]
Hi @memat100, I can't put the file on GitHub as I don't have that much quota. I have uploaded the file here : https://drive.google.com/file/d/1taWqACnXrJYBaAerhvCSLhymDti1hvbx/view?usp=sharing. You can download and place the file in `site-packages/ekphrasis/stats` directory after you install the package to get this library to work.

**Comment by memat100** [comment]
Thank you very much. But from your previous comment, I tried to retrieve it
from my cache files and I succeeded already. Anyway in both way, you saved
my time and project :)


Am Di., 21. Mai 2019 um 20:25 Uhr schrieb bhuthesh r <
notifications@github.com>:

**Comment by RemonComputer** [comment]
Hello, 
I had the same issue, I put the file at `site-packages/ekphrasis/stats` but that didn't work, I found that the package was reading from `/home/my_user_account_name/.ekphrasis/stats` so I unzipped the file in this folder and all my problems were solved, I am using Ubuntu 18.04 python3.6

**Comment by cbaziotis** [comment]
Sorry for this. I need to move the precomputed statistics from dropbox to a sever. I will do this sometime in the next week. For the moment, use the workaround proposed by @RemonComputer.

**Comment by pp-universe** [comment]
I have the same issue. Can you please update the link?https://drive.google.com/file/d/1taWqACnXrJYBaAerhvCSLhymDti1hvbx/view?usp=sharing is failure

**Comment by cbaziotis** [comment]
See here https://github.com/cbaziotis/ekphrasis/issues/28#issuecomment-1128678421
