### ISSUE TITLE
Log messages print to stdout

### ISSUE THREAD

**Issue by ckingdev** [cbaziotis/ekphrasis#2]
First just wanted to say thanks for making this available, this has been very useful- I've been working with reddit and Twitter text and this has been instrumental.

This is altogether a pretty minor issue, but there are a few places where messages are printed. I use this in a script along with GNU parallel to process line delimited json, and merge the results back into one file. So the output is mixed with the messages about loading the models, etc.

I forked this and replaced the print statements with logging calls, so that they'll go to stderr and the user can control the verbosity by setting the logging level. Would you be interested in a pull request for that? I would just need to clean up a few changes I made to keep subreddit names together (just added a regex in the pipeline). I'd be happy to share that too.

Thanks!

**Comment by cbaziotis** [comment]
Hi, 
sure i would gladly accept a PR.
