### ISSUE TITLE
Word Statistics File not Found. | Receiving 404 error while dowloading the file.

### ISSUE THREAD

**Issue by imVParashar** [cbaziotis/ekphrasis#28]
While using the library, the word statistics file is again missing from its original source: [](https://www.dropbox.com/s/a84otqrg6u1c5je/stats.zip?dl=1)

Please fix this as soon as possible and please make some more robust solutions for hosting this file. It looks like people faced this problem in the past as well.

Due to this issue, the production service is stopped. Please fix this asap!

Thanks in advance.!

**Comment by shihabshahriar16** [comment]
same issue here!

**Comment by Nick18899** [comment]
We are going to have a deploy of project on Saturday, and the tokenizer has fallen!!! Please, repair it quickly!

**Comment by asmhack** [comment]
Uncompress and put that folder into home dir. 
So should be: ~/.ekphrasis/...

https://we.tl/t-ON3T4PT3O2

**Comment by fucaja** [comment]
Hi @yistarostin, I am new to using github, could you explain how it worked for you?

Tried using !git clone https://github.com/cbaziotis/ekphrasis.git in /root/ folder in colab (see the screenshot). How can I use the library?

![ekp](https://user-images.githubusercontent.com/92200567/136646517-8184d92f-0f27-4004-996e-17f4a270b94f.PNG)

**Comment by yistarostin** [comment]
@fucaja As advised before, you need to put ekphrasis dictionary files to ```/root/ekphrasis```. In normal circumstances, it is performed automatically, but somehow it is now broken, that is why we are here in this issue. So, you need to manually download .zip archive from the link mentioned in previous comments, than upload this file to Colab to /root folder, then change directory to /root, and than unzip the archive.

**Comment by ArlanCooper** [comment]
> 

the original url has expired, can you make another new url to download the dataset,   thanks

**Comment by ArlanCooper** [comment]
> Uncompress and put that folder into home dir. So should be: ~/.ekphrasis/stats/...
> 
> https://we.tl/t-hwj94h9MMJ

the original url has expired, can you make another new url to download the dataset, thanks

**Comment by cbaziotis** [comment]
Initially, I used my personal dropbox account to host the file as only some friends and I were using the library. It turns out that dropbox has suspended my public links for generating excessive traffic...

I moved the data to another server and updated the public link for the stats.zip file. Please, ppdate the package and try again.

build from source 
```
pip install git+git://github.com/cbaziotis/ekphrasis.git
```
or install from pypi
```
pip install ekphrasis -U
```

Let me know if it works now.
