### ISSUE TITLE
Word statistics not found.....How can I solve this error?

### ISSUE THREAD

**Issue by masterbo98** [cbaziotis/ekphrasis#29]
I have uncompressed the zip you offered and put it into my home dir, and the follwing is how my category looks like. However, when I attempt to use SpellCorrector, it still reminds me that word statistics not found.
![image](https://user-images.githubusercontent.com/73686357/137419643-b8f650f2-c4a3-4cff-adcb-6873a52ac8c1.png)

**Comment by UGUESS-lzx** [comment]
Excuse me, where can I get the twitter_2018 file?😢
