### ISSUE TITLE
Ekphrasis downloads statistics in /usr/local

### ISSUE THREAD

**Issue by georgepar** [cbaziotis/ekphrasis#3]
If the user does not install ekphrasis using a virtualenv it downloads statistics in /usr/local and requires sudo permissions to run.

Statistics should be downloaded in /home/<user>/.ekphrasis to resolve this.

**Comment by nishnik** [comment]
:+1: for the change

**Comment by cbaziotis** [comment]
Fixed! Thanks geopar :+1:
