### ISSUE TITLE
how to get the word statistics?

### ISSUE THREAD

**Issue by UGUESS-lzx** [cbaziotis/ekphrasis#31]
Excuse me, where can I get the word statistics?😢
In other Issue, they said
![image](https://user-images.githubusercontent.com/63826387/147906103-3c29966f-de69-471c-a85e-8dd36c8dfb9a.png)
but I can't find the word statistics in such url...
Thanks in advance.!

**Comment by ArlanCooper** [comment]
i can't download the file by the url in the code:
https://www.dropbox.com/s/a84otqrg6u1c5je/stats.zip?dl=1
this url is inaccessible. 
where can i download this file? thanks.

**Comment by cbaziotis** [comment]
I updated the public link for the stats.zip file. Update the package and try again.

build from source 
```
pip install git+git://github.com/cbaziotis/ekphrasis.git
```
or install from pypi
```
pip install ekphrasis -U
```

Let me know if it works now.
