### ISSUE TITLE
what's wrong with "Word statistics files not found!"

### ISSUE THREAD

**Issue by lvjianwei123** [cbaziotis/ekphrasis#4]
teach me， thx

**Comment by lvjianwei123** [comment]
thx

**Comment by HqWei** [comment]
@lvjianwei123 Hi, have you solve the problem?

**Comment by llu13701** [comment]
The documentation says that the package would provide word statistics from twitter and wiki, I am wondering how to find these two stats. I cant find a folder called Stats. 

Thanks

**Comment by kkorovesis** [comment]
In my understanding, 'stats' dir is downloaded at home/<user>/.ekphrasis
