### ISSUE TITLE
Installing from pypi doesn't pull in deps

### ISSUE THREAD

**Issue by ckingdev** [cbaziotis/ekphrasis#5]
Installing with the usual

```
pip install ekphrasis
```

doesn't install `ftfy`, `termcolor`, or `colorama`. I'm guessing it doesn't install any of the dependencies, but I already had the others installed.

**Comment by cbaziotis** [comment]
Hi, I am aware of this issue. I assume that it is an easy fix. I will look into it. Thanks!

**Comment by cbaziotis** [comment]
Added requirements to setup.py. Closing issue.
